version: '3'

services:
  api-server:
    build:
      context: .
    env_file: .env
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $PORT
      BLACK_FRIDAY: $BLACK_FRIDAY
      GIFT_QUANTITY: $GIFT_QUANTITY
      GRPC_PORT: $GRPC_PORT
    volumes:
      - ./:/usr/app
    command: /usr/app/entrypoint.sh
    networks:
      - app-network
    ports:
      - '3000:3000'

networks:
  app-network:
    driver: bridge
