version: '3'

services:
  api-client:
    build:
      context: .
    container_name: api-client
    image: api-client
    restart: unless-stopped
    entrypoint: /bin/sh 'entrypoint.sh'
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $PORT
      BLACK_FRIDAY: $BLACK_FRIDAY
      GIFT_QUANTITY: $GIFT_QUANTITY
      GRPC_PORT: $GRPC_PORT
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '3000:3000'
  discount:
    image: hashorg/hash-mock-discount-service
    ports:
      - '${GRPC_PORT}:${GRPC_PORT}'
networks:
  app-network:
    driver: bridge
